//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kine.NAV {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV", ConfigurationName="NAV.TFS2NAV_Port")]
    public interface TFS2NAV_Port {
        
        // CODEGEN: Generating message contract since the wrapper name (TFS2NAV_Result) of message TFS2NAV_Result does not match the default value (TFS2NAV)
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV:TFS2NAV", ReplyAction="*")]
        Kine.NAV.TFS2NAV_Result TFS2NAV(Kine.NAV.TFS2NAV request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV:TFS2NAV", ReplyAction="*")]
        System.Threading.Tasks.Task<Kine.NAV.TFS2NAV_Result> TFS2NAVAsync(Kine.NAV.TFS2NAV request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TFS2NAV", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV", IsWrapped=true)]
    public partial class TFS2NAV {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV", Order=0)]
        public string data;
        
        public TFS2NAV() {
        }
        
        public TFS2NAV(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="TFS2NAV_Result", WrapperNamespace="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV", IsWrapped=true)]
    public partial class TFS2NAV_Result {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:microsoft-dynamics-schemas/codeunit/TFS2NAV", Order=0)]
        public string return_value;
        
        public TFS2NAV_Result() {
        }
        
        public TFS2NAV_Result(string return_value) {
            this.return_value = return_value;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TFS2NAV_PortChannel : Kine.NAV.TFS2NAV_Port, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TFS2NAV_PortClient : System.ServiceModel.ClientBase<Kine.NAV.TFS2NAV_Port>, Kine.NAV.TFS2NAV_Port {
        
        public TFS2NAV_PortClient() {
        }
        
        public TFS2NAV_PortClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TFS2NAV_PortClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFS2NAV_PortClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TFS2NAV_PortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kine.NAV.TFS2NAV_Result Kine.NAV.TFS2NAV_Port.TFS2NAV(Kine.NAV.TFS2NAV request) {
            return base.Channel.TFS2NAV(request);
        }
        
        public string TFS2NAV(string data) {
            Kine.NAV.TFS2NAV inValue = new Kine.NAV.TFS2NAV();
            inValue.data = data;
            Kine.NAV.TFS2NAV_Result retVal = ((Kine.NAV.TFS2NAV_Port)(this)).TFS2NAV(inValue);
            return retVal.return_value;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Kine.NAV.TFS2NAV_Result> Kine.NAV.TFS2NAV_Port.TFS2NAVAsync(Kine.NAV.TFS2NAV request) {
            return base.Channel.TFS2NAVAsync(request);
        }
        
        public System.Threading.Tasks.Task<Kine.NAV.TFS2NAV_Result> TFS2NAVAsync(string data) {
            Kine.NAV.TFS2NAV inValue = new Kine.NAV.TFS2NAV();
            inValue.data = data;
            return ((Kine.NAV.TFS2NAV_Port)(this)).TFS2NAVAsync(inValue);
        }
    }
}
